version: '3'

services:
  firefox:
    image: selenium/node-firefox:2.53.1
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    networks:
      - front-tier

  chrome:
    image: selenium/node-chrome:2.53.1
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    networks:
      - front-tier

  hub:
    container_name: hub
    image: selenium/hub:2.53.1
    ports:
      - "4444:4444"
    expose:
      - "4444"
    networks:
      - front-tier

  test:
    container_name: test
    image: wdio-demo
    depends_on:
      - firefox
      - chrome
    volumes:
      - ./test-reports:/wdio-demo/test-reports
    working_dir: /wdio-demo
    command: "npm test"
    networks:
      - front-tier

networks:
  front-tier:
    driver: bridge